version: '3.8'
services:
  backend:
    build:
      context: ./Backend/mern_backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/reactdata
      - PORT=4000
    volumes:
      - ./Backend/mern_backend:/usr/src/app

  frontend:
    build:
      context: ./Frontend/mern_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./Frontend/mern_frontend:/app

